variables:
  mtx: '/data/matrices/datasets/matrices_list_filtered.txt'
preprocess: |
    source ~/.venv/bin/activate

jobs:
  - config: "perm"
    config_jobs:

      - tag: "random1D"
        preprocess: |
          mtx_name=$(basename {mtx} .mtx)
          mkdir -p /data/matrices/perms/random1D
          perm_path=/data/matrices/perms/random1D/$mtx_name.perm
        command: "python3 include/external/Reordering-for-blocks/MtxPerm/RANDOM/GB_random_permutation_1d.py {mtx} $perm_path"

      - tag: "random2D"
        preprocess: |
          mtx_name=$(basename {mtx} .mtx)
          mkdir -p /data/matrices/perms/random2D
          perm_path=/data/matrices/perms/random2D/$mtx_name.perm
        command: "python3 include/external/Reordering-for-blocks/MtxPerm/RANDOM/GB_random_permutation_2d.py {mtx} $perm_path"
      # - tag: "SPARTA_reorder"  # disabled
      #   preprocess: |
      #     mtx_name=$(basename {mtx} .mtx)
      #     mkdir -p /data/matrices/perms/SPARTA_reorder
      #     perm_path=/data/matrices/perms/SPARTA_reorder/$mtx_name.perm
      #   command: "python3 include/external/Reordering-for-blocks/MtxPerm/SPARTA/reorder.py {mtx} $perm_path --block-size 32 --tau 0.5"

      - tag: "SB_amd"
        preprocess: |
          mtx_name=$(basename {mtx} .mtx)
          mkdir -p /data/matrices/perms/SB_amd
          perm_path=/data/matrices/perms/SB_amd/$mtx_name.perm
        command: "./include/external/Reordering-for-blocks/MtxPerm/SPARSEBASE/build/amd_perm {mtx} $perm_path"

      - tag: "SB_rabbit"
        preprocess: |
          mtx_name=$(basename {mtx} .mtx)
          mkdir -p /data/matrices/perms/SB_rabbit
          perm_path=/data/matrices/perms/SB_rabbit/$mtx_name.perm
        command: "./include/external/Reordering-for-blocks/MtxPerm/SPARSEBASE/build/rabbit_perm {mtx} $perm_path"

      - tag: "SB_patoh"
        preprocess: |
          mtx_name=$(basename {mtx} .mtx)
          mkdir -p /data/matrices/perms/SB_patoh
          perm_path=/data/matrices/perms/SB_patoh/$mtx_name.perm
        command: "./include/external/Reordering-for-blocks/MtxPerm/SPARSEBASE/build/patoh_perm {mtx} $perm_path --nparts 128"

      - tag: "SB_slashburn"
        preprocess: |
          mtx_name=$(basename {mtx} .mtx)
          mkdir -p /data/matrices/perms/SB_slashburn
          perm_path=/data/matrices/perms/SB_slashburn/$mtx_name.perm
        command: "./include/external/Reordering-for-blocks/MtxPerm/SPARSEBASE/build/slashburn_perm {mtx} $perm_path"

      - tag: "CLUB_reorder"
        preprocess: |
          mtx_name=$(basename {mtx} .mtx)
          mkdir -p /data/matrices/perms/CLUB_reorder
          perm_path=/data/matrices/perms/CLUB_reorder/$mtx_name.perm
        command: "python3 include/external/Reordering-for-blocks/MtxPerm/CLUB/reorder.py {mtx} $perm_path"

      # - tag: "ACCORDER_reorder"  # disabled
      #   preprocess: |
      #     source include/external/Reordering-for-blocks/MtxPerm/ACCORDER/accorder_preprocess.sh
      #     mtx_name=$(basename {mtx} .mtx)
      #     mkdir -p /data/matrices/perms/ACCORDER_reorder
      #     perm_path=/data/matrices/perms/ACCORDER_reorder/$mtx_name.perm
      #   command: "./include/external/Reordering-for-blocks/MtxPerm/ACCORDER/build/accorder_perm {mtx} $perm_path"

  - config: "gpu"
    config_jobs:
      - tag: "TCA_reorder"
        preprocess: |
          source include/external/Reordering-for-blocks/MtxPerm/DTC-LSH/tca_preprocess.sh
          mtx_name=$(basename {mtx} .mtx)
          mkdir -p /data/matrices/perms/TCA_reorder
          perm_path=/data/matrices/perms/TCA_reorder/$mtx_name.perm
        command: "python3 include/external/Reordering-for-blocks/MtxPerm/DTC-LSH/reorder.py {mtx} $perm_path"